language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull mysql:5.7
  - docker run -d --rm -p3307:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=gather2gether -e MYSQL_USER=g2g -e MYSQL_PASSWORD=g2g mysql:5.7
  - docker ps -a

install:
  - pip install Jinja2
  - python setup.py install

before_script:
  - pip install nose

script:
- nosetests -v --with-coverage --cover-package=gather2gether --cover-inclusive --with-xunit
